import { IActionsTypes } from "../interfaces/interfaces";

export const ActionTypes: IActionsTypes = {
  GET_ALL_CONTACTS : 'GET_ALL_CONTACTS',
  GET_ALL_CONTACTS_SUCCESS: 'GET_ALL_CONTACTS_SUCCESS',
  GET_CONTACT_BY_ID: 'GET_CONTACT_BY_ID',
  GET_CONTACT_BY_ID_SUCCESS: 'GET_CONTACT_BY_ID_SUCCESS', 
  DELETE_CONTACT_BY_ID: 'DELETE_CONTACT_BY_ID',
  UPDATE_CONTACT_BY_ID: 'UPDATE_CONTACT_BY_ID'
}

